# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         gearmand
version:      1.01
version_from: gearmand
installdirs:  site
requires:
    Danga::Socket:                 1.5
    Gearman::Util:                 0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
